// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG8vRXet0Ny0Hjf53wYeDdpUctvR0ooAA',
    appId: '1:662625991254:web:a8dcd2c785132137f199f7',
    messagingSenderId: '662625991254',
    projectId: 'signlanguage-bac86',
    authDomain: 'signlanguage-bac86.firebaseapp.com',
    storageBucket: 'signlanguage-bac86.firebasestorage.app',
    measurementId: 'G-H9ME1M88W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLBWS274id69jtKvaAumPdIXO19I_aOio',
    appId: '1:662625991254:android:89628b190b6dfae3f199f7',
    messagingSenderId: '662625991254',
    projectId: 'signlanguage-bac86',
    storageBucket: 'signlanguage-bac86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnZc_LzcRwQs3tmqCY0IzHGo-3-0GanU',
    appId: '1:662625991254:ios:0b994e999ce58e8ef199f7',
    messagingSenderId: '662625991254',
    projectId: 'signlanguage-bac86',
    storageBucket: 'signlanguage-bac86.firebasestorage.app',
    iosClientId: '662625991254-t0nkb3bdcm6l4kd9he452k749f5qg0m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnZc_LzcRwQs3tmqCY0IzHGo-3-0GanU',
    appId: '1:662625991254:ios:0b994e999ce58e8ef199f7',
    messagingSenderId: '662625991254',
    projectId: 'signlanguage-bac86',
    storageBucket: 'signlanguage-bac86.firebasestorage.app',
    iosClientId: '662625991254-t0nkb3bdcm6l4kd9he452k749f5qg0m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG8vRXet0Ny0Hjf53wYeDdpUctvR0ooAA',
    appId: '1:662625991254:web:16a921261755d981f199f7',
    messagingSenderId: '662625991254',
    projectId: 'signlanguage-bac86',
    authDomain: 'signlanguage-bac86.firebaseapp.com',
    storageBucket: 'signlanguage-bac86.firebasestorage.app',
    measurementId: 'G-X1WW5L1F9J',
  );
}
